# Generated by Django 5.0.4 on 2024-05-31 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "Ca_id",
                    models.AutoField(
                        auto_created=True,
                        default=None,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "Co_id",
                    models.AutoField(
                        auto_created=True,
                        default=None,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("subject", models.CharField(max_length=200, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "date_sent",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date Sent"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "I_id",
                    models.AutoField(
                        auto_created=True,
                        default=None,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="static\\DB_upload")),
                ("description", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Zyenex_A.category",
                    ),
                ),
            ],
        ),
    ]
