# Generated by Django 5.0.4 on 2024-06-03 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Zyenex_A", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "Order_ID",
                    models.AutoField(
                        auto_created=True,
                        default=None,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "portfolio_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Zyenex_A.items"
                    ),
                ),
            ],
        ),
    ]
