# Generated by Django 5.0.4 on 2024-06-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Zyenex_A", "0004_items_video_alter_items_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="static\\DB_upload\\videos"
            ),
        ),
    ]
